---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3-50-gd56c40f
_src_path: /Users/kamontat/Desktop/Personal/asdf-plugin-template
app_desc: local clusters for testing Kubernetes
app_name: kind
app_repo: https://github.com/kubernetes-sigs/kind
app_website: https://kind.sigs.k8s.io/
archive_enabled: false
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/kubernetes-sigs/kind/releases/download/v{version}/kind-{os}-{arch}.sha256sum
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm64
    armv6*: arm64
    armv7*: arm64
    x86_64: amd64
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
custom_require_commands: ''
download_url: https://github.com/kubernetes-sigs/kind/releases/download/v{version}/kind-{os}-{arch}
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    kind: bin/kind
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-kind
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-kind.git
source_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
